# Generated by Django 4.0.2 on 2023-06-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_bookcustomfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='BookCustomField',
        ),
    ]
