# Generated by Django 4.0.2 on 2023-10-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_book_metadata_delete_bookcustomfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
